# Generated by Django 6.0 on 2026-01-14 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='best_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.posts'),
        ),
        migrations.AddConstraint(
            model_name='director',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'email_address'), name='unique_details'),
        ),
    ]
