# Generated by Django 6.0 on 2026-01-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_director_best_film_director_unique_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'Director Details'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Post Details'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
