# Generated by Django 6.0 on 2026-01-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_director_options_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(max_length=4000),
        ),
    ]
